# Generated by Django 3.2.9 on 2022-02-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20220211_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_post',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
