# Generated by Django 3.2.9 on 2022-02-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20220213_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportantPoints',
            new_name='ImportantPoint',
        ),
    ]
