# Generated by Django 3.2.9 on 2022-02-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_rename_importantpoints_importantpoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
    ]
