# Generated by Django 3.2.9 on 2022-02-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
