# Generated by Django 3.2.9 on 2022-02-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
