# Generated by Django 3.2.9 on 2022-02-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post'),
        ),
    ]
