# Generated by Django 3.2.9 on 2022-02-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_auto_20220214_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
