# Generated by Django 3.2.5 on 2022-02-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0026_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_p1',
        ),
        migrations.AddField(
            model_name='post',
            name='content_p2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_p3',
            field=models.TextField(null=True),
        ),
    ]
