# Generated by Django 3.2.5 on 2022-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_auto_20220217_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='post_image_1',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_2',
            field=models.ImageField(null=True, upload_to='post/post-image/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_3',
            field=models.ImageField(null=True, upload_to='post/post-image/'),
        ),
    ]
