# Generated by Django 3.2.5 on 2022-02-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_auto_20220217_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighLight',
        ),
    ]
