# Generated by Django 3.2.5 on 2022-02-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0030_delete_highlight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='topic_1',
        ),
        migrations.AddField(
            model_name='post',
            name='topic_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='topic_3',
            field=models.TextField(null=True),
        ),
    ]
