# Generated by Django 3.2.5 on 2022-02-18 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0032_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upload_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
