# Generated by Django 3.2.5 on 2022-02-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0033_comment_upload_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic_3',
        ),
    ]
