# Generated by Django 3.2.5 on 2022-02-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0034_auto_20220218_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic_1',
            new_name='content',
        ),
    ]
