# Generated by Django 3.1.4 on 2022-03-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0038_auto_20220310_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
